### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [DRAMCO/Dramco-UNO#1]
In the files:
- Dramco-UNO/Dramco-UNO/Dramco-UNO.ino
- Dramco-UNO/Accelero-Test/Accelero-Test.ino

the Wire.requestFrom() is followed by a Wire.endTransmission(). That Wire.endTransmission() at the end of the function can be removed. Also a Wire.beginTransmission() should not be used before a Wire.requestFrom().
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 2 and 3.

**Comment by GillesC** [comment]
@BartThoen 

If I am correct, we should remove these lines:

https://github.com/DRAMCO/Dramco-UNO/blob/154ab29cc6e2b9cfb34cef466507e962b0f7328a/Dramco-UNO/Dramco-UNO.ino#L384

https://github.com/DRAMCO/Dramco-UNO/blob/154ab29cc6e2b9cfb34cef466507e962b0f7328a/Dramco-UNO/Dramco-UNO.ino#L377

**Comment by Koepel** [comment]
Yes, those lines in "Dramco-UNO.ino".

In "Accelero-Test.ino" it is line [104](https://github.com/DRAMCO/Dramco-UNO/blob/master/Accelero-Test/Accelero-Test.ino#L104) and [113](https://github.com/DRAMCO/Dramco-UNO/blob/master/Accelero-Test/Accelero-Test.ino#L113) at the moment.

**Comment by GillesC** [comment]
@Koepel , thank you for the contribution!
